#ifndef LAPI_APPLICATION_H_INCLUDED
#define LAPI_APPLICATION_H_INCLUDED

#define LAPI_APPLICATION_APP "_app"
#define LAPI_APPLICATION_APP_PATH "_app_path"
#define LAPI_APPLICATION_APP_ROUTE "_route"

ZEND_MINIT_FUNCTION(lapi_application);


#endif // LAPI_APPLICATION_H_INCLUDED
